

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class Instructor : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass>
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Instructor()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Instructor(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Instructor> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Instructor.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Instructor_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Instructor_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Instructor.DetailsClass.GetValue(this, global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Instructor.DetailsClass.SetValue(this, global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string FirstName
        {
            get
            {
                return global::LightSwitchApplication.Instructor.DetailsClass.GetValue(this, global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.FirstName);
            }
            set
            {
                global::LightSwitchApplication.Instructor.DetailsClass.SetValue(this, global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.FirstName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FirstName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FirstName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FirstName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string LastName
        {
            get
            {
                return global::LightSwitchApplication.Instructor.DetailsClass.GetValue(this, global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.LastName);
            }
            set
            {
                global::LightSwitchApplication.Instructor.DetailsClass.SetValue(this, global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.LastName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LastName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LastName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LastName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Title
        {
            get
            {
                return global::LightSwitchApplication.Instructor.DetailsClass.GetValue(this, global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.Title);
            }
            set
            {
                global::LightSwitchApplication.Instructor.DetailsClass.SetValue(this, global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.Title, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] Picture
        {
            get
            {
                return global::LightSwitchApplication.Instructor.DetailsClass.GetValue(this, global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.Picture);
            }
            set
            {
                global::LightSwitchApplication.Instructor.DetailsClass.SetValue(this, global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.Picture, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Picture_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Picture_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Picture_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Phone
        {
            get
            {
                return global::LightSwitchApplication.Instructor.DetailsClass.GetValue(this, global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.Phone);
            }
            set
            {
                global::LightSwitchApplication.Instructor.DetailsClass.SetValue(this, global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.Phone, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Phone_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Phone_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Phone_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Office
        {
            get
            {
                return global::LightSwitchApplication.Instructor.DetailsClass.GetValue(this, global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.Office);
            }
            set
            {
                global::LightSwitchApplication.Instructor.DetailsClass.SetValue(this, global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.Office, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Office_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Office_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Office_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Bio
        {
            get
            {
                return global::LightSwitchApplication.Instructor.DetailsClass.GetValue(this, global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.Bio);
            }
            set
            {
                global::LightSwitchApplication.Instructor.DetailsClass.SetValue(this, global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.Bio, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Bio_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Bio_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Bio_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime CreatedTime
        {
            get
            {
                return global::LightSwitchApplication.Instructor.DetailsClass.GetValue(this, global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.CreatedTime);
            }
            set
            {
                global::LightSwitchApplication.Instructor.DetailsClass.SetValue(this, global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.CreatedTime, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedTime_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedTime_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedTime_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime UpdatedTime
        {
            get
            {
                return global::LightSwitchApplication.Instructor.DetailsClass.GetValue(this, global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.UpdatedTime);
            }
            set
            {
                global::LightSwitchApplication.Instructor.DetailsClass.SetValue(this, global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.UpdatedTime, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UpdatedTime_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UpdatedTime_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UpdatedTime_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string UpdatedBy
        {
            get
            {
                return global::LightSwitchApplication.Instructor.DetailsClass.GetValue(this, global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.UpdatedBy);
            }
            set
            {
                global::LightSwitchApplication.Instructor.DetailsClass.SetValue(this, global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.UpdatedBy, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UpdatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UpdatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UpdatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Summary
        {
            get
            {
                return global::LightSwitchApplication.Instructor.DetailsClass.GetValue(this, global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.Summary);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Summary_Compute(ref string result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Summary_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Section> Sections
        {
            get
            {
                return global::LightSwitchApplication.Instructor.DetailsClass.GetValue(this, global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.Sections);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Section> SectionsQuery
        {
            get
            {
                return global::LightSwitchApplication.Instructor.DetailsClass.GetQuery(this, global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.Sections);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Instructor,
                global::LightSwitchApplication.Instructor.DetailsClass,
                global::LightSwitchApplication.Instructor.DetailsClass.IImplementation,
                global::LightSwitchApplication.Instructor.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass>.Entry
                __InstructorEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass>.Entry(
                    global::LightSwitchApplication.Instructor.DetailsClass.__Instructor_CreateNew,
                    global::LightSwitchApplication.Instructor.DetailsClass.__Instructor_Created,
                    global::LightSwitchApplication.Instructor.DetailsClass.__Instructor_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Instructor __Instructor_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Instructor> es)
            {
                return new global::LightSwitchApplication.Instructor(es);
            }
            private static void __Instructor_Created(global::LightSwitchApplication.Instructor e)
            {
                e.Instructor_Created();
            }
            private static bool __Instructor_AllowSaveWithErrors(global::LightSwitchApplication.Instructor e)
            {
                bool result = false;
                e.Instructor_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Instructor.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string> FirstName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.FirstName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string> LastName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.LastName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string> Title
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.Title) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, byte[]> Picture
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.Picture) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string> Phone
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.Phone) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string> Office
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.Office) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string> Bio
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.Bio) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, global::System.DateTime> CreatedTime
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.CreatedTime) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, global::System.DateTime> UpdatedTime
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.UpdatedTime) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string> UpdatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.UpdatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string> Summary
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.Summary) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, global::LightSwitchApplication.Section> Sections
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.Sections) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, global::LightSwitchApplication.Section>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string FirstName { get; set; }
                new string LastName { get; set; }
                new string Title { get; set; }
                new byte[] Picture { get; set; }
                new string Phone { get; set; }
                new string Office { get; set; }
                new string Bio { get; set; }
                new global::System.DateTime CreatedTime { get; set; }
                new global::System.DateTime UpdatedTime { get; set; }
                new string UpdatedBy { get; set; }
                new global::System.Collections.IEnumerable Sections { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Instructor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, int>.Data> c, global::LightSwitchApplication.Instructor.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Instructor e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Instructor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Instructor.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Instructor.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Instructor e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Entry
                    FirstName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Entry(
                        "FirstName",
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._FirstName_Stub,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._FirstName_ComputeIsReadOnly,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._FirstName_Validate,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._FirstName_GetImplementationValue,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._FirstName_SetImplementationValue,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._FirstName_OnValueChanged);
                private static void _FirstName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Instructor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Data> c, global::LightSwitchApplication.Instructor.DetailsClass d, object sf)
                {
                    c(d, ref d._FirstName, sf);
                }
                private static bool _FirstName_ComputeIsReadOnly(global::LightSwitchApplication.Instructor e)
                {
                    bool result = false;
                    e.FirstName_IsReadOnly(ref result);
                    return result;
                }
                private static void _FirstName_Validate(global::LightSwitchApplication.Instructor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.FirstName_Validate(r);
                }
                private static string _FirstName_GetImplementationValue(global::LightSwitchApplication.Instructor.DetailsClass d)
                {
                    return d.ImplementationEntity.FirstName;
                }
                private static void _FirstName_SetImplementationValue(global::LightSwitchApplication.Instructor.DetailsClass d, string v)
                {
                    d.ImplementationEntity.FirstName = v;
                }
                private static void _FirstName_OnValueChanged(global::LightSwitchApplication.Instructor e)
                {
                    e.FirstName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Entry
                    LastName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Entry(
                        "LastName",
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._LastName_Stub,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._LastName_ComputeIsReadOnly,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._LastName_Validate,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._LastName_GetImplementationValue,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._LastName_SetImplementationValue,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._LastName_OnValueChanged);
                private static void _LastName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Instructor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Data> c, global::LightSwitchApplication.Instructor.DetailsClass d, object sf)
                {
                    c(d, ref d._LastName, sf);
                }
                private static bool _LastName_ComputeIsReadOnly(global::LightSwitchApplication.Instructor e)
                {
                    bool result = false;
                    e.LastName_IsReadOnly(ref result);
                    return result;
                }
                private static void _LastName_Validate(global::LightSwitchApplication.Instructor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.LastName_Validate(r);
                }
                private static string _LastName_GetImplementationValue(global::LightSwitchApplication.Instructor.DetailsClass d)
                {
                    return d.ImplementationEntity.LastName;
                }
                private static void _LastName_SetImplementationValue(global::LightSwitchApplication.Instructor.DetailsClass d, string v)
                {
                    d.ImplementationEntity.LastName = v;
                }
                private static void _LastName_OnValueChanged(global::LightSwitchApplication.Instructor e)
                {
                    e.LastName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Entry
                    Title = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Entry(
                        "Title",
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Title_Stub,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Title_ComputeIsReadOnly,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Title_Validate,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Title_GetImplementationValue,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Title_SetImplementationValue,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Title_OnValueChanged);
                private static void _Title_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Instructor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Data> c, global::LightSwitchApplication.Instructor.DetailsClass d, object sf)
                {
                    c(d, ref d._Title, sf);
                }
                private static bool _Title_ComputeIsReadOnly(global::LightSwitchApplication.Instructor e)
                {
                    bool result = false;
                    e.Title_IsReadOnly(ref result);
                    return result;
                }
                private static void _Title_Validate(global::LightSwitchApplication.Instructor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Title_Validate(r);
                }
                private static string _Title_GetImplementationValue(global::LightSwitchApplication.Instructor.DetailsClass d)
                {
                    return d.ImplementationEntity.Title;
                }
                private static void _Title_SetImplementationValue(global::LightSwitchApplication.Instructor.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Title = v;
                }
                private static void _Title_OnValueChanged(global::LightSwitchApplication.Instructor e)
                {
                    e.Title_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, byte[]>.Entry
                    Picture = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, byte[]>.Entry(
                        "Picture",
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Picture_Stub,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Picture_ComputeIsReadOnly,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Picture_Validate,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Picture_GetImplementationValue,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Picture_SetImplementationValue,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Picture_OnValueChanged);
                private static void _Picture_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Instructor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Instructor.DetailsClass d, object sf)
                {
                    c(d, ref d._Picture, sf);
                }
                private static bool _Picture_ComputeIsReadOnly(global::LightSwitchApplication.Instructor e)
                {
                    bool result = false;
                    e.Picture_IsReadOnly(ref result);
                    return result;
                }
                private static void _Picture_Validate(global::LightSwitchApplication.Instructor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Picture_Validate(r);
                }
                private static byte[] _Picture_GetImplementationValue(global::LightSwitchApplication.Instructor.DetailsClass d)
                {
                    return d.ImplementationEntity.Picture;
                }
                private static void _Picture_SetImplementationValue(global::LightSwitchApplication.Instructor.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.Picture = v;
                }
                private static void _Picture_OnValueChanged(global::LightSwitchApplication.Instructor e)
                {
                    e.Picture_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Entry
                    Phone = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Entry(
                        "Phone",
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Phone_Stub,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Phone_ComputeIsReadOnly,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Phone_Validate,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Phone_GetImplementationValue,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Phone_SetImplementationValue,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Phone_OnValueChanged);
                private static void _Phone_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Instructor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Data> c, global::LightSwitchApplication.Instructor.DetailsClass d, object sf)
                {
                    c(d, ref d._Phone, sf);
                }
                private static bool _Phone_ComputeIsReadOnly(global::LightSwitchApplication.Instructor e)
                {
                    bool result = false;
                    e.Phone_IsReadOnly(ref result);
                    return result;
                }
                private static void _Phone_Validate(global::LightSwitchApplication.Instructor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Phone_Validate(r);
                }
                private static string _Phone_GetImplementationValue(global::LightSwitchApplication.Instructor.DetailsClass d)
                {
                    return d.ImplementationEntity.Phone;
                }
                private static void _Phone_SetImplementationValue(global::LightSwitchApplication.Instructor.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Phone = v;
                }
                private static void _Phone_OnValueChanged(global::LightSwitchApplication.Instructor e)
                {
                    e.Phone_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Entry
                    Office = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Entry(
                        "Office",
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Office_Stub,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Office_ComputeIsReadOnly,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Office_Validate,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Office_GetImplementationValue,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Office_SetImplementationValue,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Office_OnValueChanged);
                private static void _Office_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Instructor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Data> c, global::LightSwitchApplication.Instructor.DetailsClass d, object sf)
                {
                    c(d, ref d._Office, sf);
                }
                private static bool _Office_ComputeIsReadOnly(global::LightSwitchApplication.Instructor e)
                {
                    bool result = false;
                    e.Office_IsReadOnly(ref result);
                    return result;
                }
                private static void _Office_Validate(global::LightSwitchApplication.Instructor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Office_Validate(r);
                }
                private static string _Office_GetImplementationValue(global::LightSwitchApplication.Instructor.DetailsClass d)
                {
                    return d.ImplementationEntity.Office;
                }
                private static void _Office_SetImplementationValue(global::LightSwitchApplication.Instructor.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Office = v;
                }
                private static void _Office_OnValueChanged(global::LightSwitchApplication.Instructor e)
                {
                    e.Office_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Entry
                    Bio = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Entry(
                        "Bio",
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Bio_Stub,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Bio_ComputeIsReadOnly,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Bio_Validate,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Bio_GetImplementationValue,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Bio_SetImplementationValue,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Bio_OnValueChanged);
                private static void _Bio_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Instructor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Data> c, global::LightSwitchApplication.Instructor.DetailsClass d, object sf)
                {
                    c(d, ref d._Bio, sf);
                }
                private static bool _Bio_ComputeIsReadOnly(global::LightSwitchApplication.Instructor e)
                {
                    bool result = false;
                    e.Bio_IsReadOnly(ref result);
                    return result;
                }
                private static void _Bio_Validate(global::LightSwitchApplication.Instructor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Bio_Validate(r);
                }
                private static string _Bio_GetImplementationValue(global::LightSwitchApplication.Instructor.DetailsClass d)
                {
                    return d.ImplementationEntity.Bio;
                }
                private static void _Bio_SetImplementationValue(global::LightSwitchApplication.Instructor.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Bio = v;
                }
                private static void _Bio_OnValueChanged(global::LightSwitchApplication.Instructor e)
                {
                    e.Bio_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, global::System.DateTime>.Entry
                    CreatedTime = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, global::System.DateTime>.Entry(
                        "CreatedTime",
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._CreatedTime_Stub,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._CreatedTime_ComputeIsReadOnly,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._CreatedTime_Validate,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._CreatedTime_GetImplementationValue,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._CreatedTime_SetImplementationValue,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._CreatedTime_OnValueChanged);
                private static void _CreatedTime_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Instructor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.Instructor.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedTime, sf);
                }
                private static bool _CreatedTime_ComputeIsReadOnly(global::LightSwitchApplication.Instructor e)
                {
                    bool result = false;
                    e.CreatedTime_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedTime_Validate(global::LightSwitchApplication.Instructor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedTime_Validate(r);
                }
                private static global::System.DateTime _CreatedTime_GetImplementationValue(global::LightSwitchApplication.Instructor.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedTime;
                }
                private static void _CreatedTime_SetImplementationValue(global::LightSwitchApplication.Instructor.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.CreatedTime = global::LightSwitchApplication.Instructor.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _CreatedTime_OnValueChanged(global::LightSwitchApplication.Instructor e)
                {
                    e.CreatedTime_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, global::System.DateTime>.Entry
                    UpdatedTime = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, global::System.DateTime>.Entry(
                        "UpdatedTime",
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._UpdatedTime_Stub,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._UpdatedTime_ComputeIsReadOnly,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._UpdatedTime_Validate,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._UpdatedTime_GetImplementationValue,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._UpdatedTime_SetImplementationValue,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._UpdatedTime_OnValueChanged);
                private static void _UpdatedTime_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Instructor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.Instructor.DetailsClass d, object sf)
                {
                    c(d, ref d._UpdatedTime, sf);
                }
                private static bool _UpdatedTime_ComputeIsReadOnly(global::LightSwitchApplication.Instructor e)
                {
                    bool result = false;
                    e.UpdatedTime_IsReadOnly(ref result);
                    return result;
                }
                private static void _UpdatedTime_Validate(global::LightSwitchApplication.Instructor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.UpdatedTime_Validate(r);
                }
                private static global::System.DateTime _UpdatedTime_GetImplementationValue(global::LightSwitchApplication.Instructor.DetailsClass d)
                {
                    return d.ImplementationEntity.UpdatedTime;
                }
                private static void _UpdatedTime_SetImplementationValue(global::LightSwitchApplication.Instructor.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.UpdatedTime = global::LightSwitchApplication.Instructor.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _UpdatedTime_OnValueChanged(global::LightSwitchApplication.Instructor e)
                {
                    e.UpdatedTime_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Entry
                    UpdatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Entry(
                        "UpdatedBy",
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._UpdatedBy_Stub,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._UpdatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._UpdatedBy_Validate,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._UpdatedBy_GetImplementationValue,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._UpdatedBy_SetImplementationValue,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._UpdatedBy_OnValueChanged);
                private static void _UpdatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Instructor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Data> c, global::LightSwitchApplication.Instructor.DetailsClass d, object sf)
                {
                    c(d, ref d._UpdatedBy, sf);
                }
                private static bool _UpdatedBy_ComputeIsReadOnly(global::LightSwitchApplication.Instructor e)
                {
                    bool result = false;
                    e.UpdatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _UpdatedBy_Validate(global::LightSwitchApplication.Instructor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.UpdatedBy_Validate(r);
                }
                private static string _UpdatedBy_GetImplementationValue(global::LightSwitchApplication.Instructor.DetailsClass d)
                {
                    return d.ImplementationEntity.UpdatedBy;
                }
                private static void _UpdatedBy_SetImplementationValue(global::LightSwitchApplication.Instructor.DetailsClass d, string v)
                {
                    d.ImplementationEntity.UpdatedBy = v;
                }
                private static void _UpdatedBy_OnValueChanged(global::LightSwitchApplication.Instructor e)
                {
                    e.UpdatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Entry
                    Summary = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Entry(
                        "Summary",
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Summary_Stub,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Summary_Validate,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Summary_ComputeValue);
                private static void _Summary_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Instructor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Data> c, global::LightSwitchApplication.Instructor.DetailsClass d, object sf)
                {
                    c(d, ref d._Summary, sf);
                }
                private static void _Summary_Validate(global::LightSwitchApplication.Instructor e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Summary_Validate(r);
                }
                private static string _Summary_ComputeValue(global::LightSwitchApplication.Instructor e)
                {
                    string value = default(string);
                    e.Summary_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, global::LightSwitchApplication.Section>.Entry
                    Sections = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, global::LightSwitchApplication.Section>.Entry(
                        "Sections",
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Sections_Stub,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Sections_GetReferencedEntities,
                        global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties._Sections_GetEntityCollection);
                private static void _Sections_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Instructor.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, global::LightSwitchApplication.Section>.Data> c, global::LightSwitchApplication.Instructor.DetailsClass d, object sf)
                {
                    c(d, ref d._Sections, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Section> _Sections_GetReferencedEntities(global::LightSwitchApplication.Instructor.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Section, global::LightSwitchApplication.Section.DetailsClass>(global::LightSwitchApplication.Instructor.DetailsClass.PropertySetProperties.Sections, ref d._Sections);
                }
                private static global::System.Collections.IEnumerable _Sections_GetEntityCollection(global::LightSwitchApplication.Instructor.DetailsClass d)
                {
                    return d.ImplementationEntity.Sections;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Data _FirstName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Data _LastName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Data _Title;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, byte[]>.Data _Picture;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Data _Phone;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Data _Office;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Data _Bio;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, global::System.DateTime>.Data _CreatedTime;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, global::System.DateTime>.Data _UpdatedTime;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Data _UpdatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, string>.Data _Summary;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Instructor, global::LightSwitchApplication.Instructor.DetailsClass, global::LightSwitchApplication.Section>.Data _Sections;
            
        }
    
        #endregion
    }
    
    #endregion
}
