

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class Student : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass>
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Student()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Student(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Student> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Student.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Student_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Student_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Student.DetailsClass.GetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Student.DetailsClass.SetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string FirstName
        {
            get
            {
                return global::LightSwitchApplication.Student.DetailsClass.GetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.FirstName);
            }
            set
            {
                global::LightSwitchApplication.Student.DetailsClass.SetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.FirstName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FirstName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FirstName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FirstName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string LastName
        {
            get
            {
                return global::LightSwitchApplication.Student.DetailsClass.GetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.LastName);
            }
            set
            {
                global::LightSwitchApplication.Student.DetailsClass.SetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.LastName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LastName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LastName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LastName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Email
        {
            get
            {
                return global::LightSwitchApplication.Student.DetailsClass.GetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Email);
            }
            set
            {
                global::LightSwitchApplication.Student.DetailsClass.SetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Email, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Email_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Email_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Email_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Phone
        {
            get
            {
                return global::LightSwitchApplication.Student.DetailsClass.GetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Phone);
            }
            set
            {
                global::LightSwitchApplication.Student.DetailsClass.SetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Phone, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Phone_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Phone_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Phone_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] Picture
        {
            get
            {
                return global::LightSwitchApplication.Student.DetailsClass.GetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Picture);
            }
            set
            {
                global::LightSwitchApplication.Student.DetailsClass.SetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Picture, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Picture_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Picture_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Picture_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Street
        {
            get
            {
                return global::LightSwitchApplication.Student.DetailsClass.GetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Street);
            }
            set
            {
                global::LightSwitchApplication.Student.DetailsClass.SetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Street, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Street_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Street_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Street_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string City
        {
            get
            {
                return global::LightSwitchApplication.Student.DetailsClass.GetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.City);
            }
            set
            {
                global::LightSwitchApplication.Student.DetailsClass.SetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.City, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void City_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void City_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void City_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string State
        {
            get
            {
                return global::LightSwitchApplication.Student.DetailsClass.GetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.State);
            }
            set
            {
                global::LightSwitchApplication.Student.DetailsClass.SetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.State, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void State_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void State_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void State_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Zip
        {
            get
            {
                return global::LightSwitchApplication.Student.DetailsClass.GetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Zip);
            }
            set
            {
                global::LightSwitchApplication.Student.DetailsClass.SetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Zip, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Zip_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Zip_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Zip_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime CreatedTime
        {
            get
            {
                return global::LightSwitchApplication.Student.DetailsClass.GetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.CreatedTime);
            }
            set
            {
                global::LightSwitchApplication.Student.DetailsClass.SetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.CreatedTime, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedTime_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedTime_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedTime_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime UpdatedTime
        {
            get
            {
                return global::LightSwitchApplication.Student.DetailsClass.GetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.UpdatedTime);
            }
            set
            {
                global::LightSwitchApplication.Student.DetailsClass.SetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.UpdatedTime, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UpdatedTime_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UpdatedTime_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UpdatedTime_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string UpdatedBy
        {
            get
            {
                return global::LightSwitchApplication.Student.DetailsClass.GetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.UpdatedBy);
            }
            set
            {
                global::LightSwitchApplication.Student.DetailsClass.SetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.UpdatedBy, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UpdatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UpdatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UpdatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Summary
        {
            get
            {
                return global::LightSwitchApplication.Student.DetailsClass.GetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Summary);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Summary_Compute(ref string result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Summary_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Enrollment> Enrollments
        {
            get
            {
                return global::LightSwitchApplication.Student.DetailsClass.GetValue(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Enrollments);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Enrollment> EnrollmentsQuery
        {
            get
            {
                return global::LightSwitchApplication.Student.DetailsClass.GetQuery(this, global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Enrollments);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Student,
                global::LightSwitchApplication.Student.DetailsClass,
                global::LightSwitchApplication.Student.DetailsClass.IImplementation,
                global::LightSwitchApplication.Student.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass>.Entry
                __StudentEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass>.Entry(
                    global::LightSwitchApplication.Student.DetailsClass.__Student_CreateNew,
                    global::LightSwitchApplication.Student.DetailsClass.__Student_Created,
                    global::LightSwitchApplication.Student.DetailsClass.__Student_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Student __Student_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Student> es)
            {
                return new global::LightSwitchApplication.Student(es);
            }
            private static void __Student_Created(global::LightSwitchApplication.Student e)
            {
                e.Student_Created();
            }
            private static bool __Student_AllowSaveWithErrors(global::LightSwitchApplication.Student e)
            {
                bool result = false;
                e.Student_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Student.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string> FirstName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.FirstName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string> LastName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.LastName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string> Email
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Email) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string> Phone
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Phone) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, byte[]> Picture
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Picture) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string> Street
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Street) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string> City
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.City) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string> State
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.State) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string> Zip
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Zip) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::System.DateTime> CreatedTime
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.CreatedTime) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::System.DateTime> UpdatedTime
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.UpdatedTime) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string> UpdatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.UpdatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string> Summary
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Summary) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::LightSwitchApplication.Enrollment> Enrollments
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Enrollments) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::LightSwitchApplication.Enrollment>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string FirstName { get; set; }
                new string LastName { get; set; }
                new string Email { get; set; }
                new string Phone { get; set; }
                new byte[] Picture { get; set; }
                new string Street { get; set; }
                new string City { get; set; }
                new string State { get; set; }
                new string Zip { get; set; }
                new global::System.DateTime CreatedTime { get; set; }
                new global::System.DateTime UpdatedTime { get; set; }
                new string UpdatedBy { get; set; }
                new global::System.Collections.IEnumerable Enrollments { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Student.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, int>.Data> c, global::LightSwitchApplication.Student.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Student e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Student e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Student e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry
                    FirstName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry(
                        "FirstName",
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._FirstName_Stub,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._FirstName_ComputeIsReadOnly,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._FirstName_Validate,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._FirstName_GetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._FirstName_SetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._FirstName_OnValueChanged);
                private static void _FirstName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Student.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data> c, global::LightSwitchApplication.Student.DetailsClass d, object sf)
                {
                    c(d, ref d._FirstName, sf);
                }
                private static bool _FirstName_ComputeIsReadOnly(global::LightSwitchApplication.Student e)
                {
                    bool result = false;
                    e.FirstName_IsReadOnly(ref result);
                    return result;
                }
                private static void _FirstName_Validate(global::LightSwitchApplication.Student e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.FirstName_Validate(r);
                }
                private static string _FirstName_GetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d)
                {
                    return d.ImplementationEntity.FirstName;
                }
                private static void _FirstName_SetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d, string v)
                {
                    d.ImplementationEntity.FirstName = v;
                }
                private static void _FirstName_OnValueChanged(global::LightSwitchApplication.Student e)
                {
                    e.FirstName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry
                    LastName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry(
                        "LastName",
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._LastName_Stub,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._LastName_ComputeIsReadOnly,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._LastName_Validate,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._LastName_GetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._LastName_SetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._LastName_OnValueChanged);
                private static void _LastName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Student.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data> c, global::LightSwitchApplication.Student.DetailsClass d, object sf)
                {
                    c(d, ref d._LastName, sf);
                }
                private static bool _LastName_ComputeIsReadOnly(global::LightSwitchApplication.Student e)
                {
                    bool result = false;
                    e.LastName_IsReadOnly(ref result);
                    return result;
                }
                private static void _LastName_Validate(global::LightSwitchApplication.Student e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.LastName_Validate(r);
                }
                private static string _LastName_GetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d)
                {
                    return d.ImplementationEntity.LastName;
                }
                private static void _LastName_SetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d, string v)
                {
                    d.ImplementationEntity.LastName = v;
                }
                private static void _LastName_OnValueChanged(global::LightSwitchApplication.Student e)
                {
                    e.LastName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry
                    Email = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry(
                        "Email",
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Email_Stub,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Email_ComputeIsReadOnly,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Email_Validate,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Email_GetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Email_SetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Email_OnValueChanged);
                private static void _Email_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Student.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data> c, global::LightSwitchApplication.Student.DetailsClass d, object sf)
                {
                    c(d, ref d._Email, sf);
                }
                private static bool _Email_ComputeIsReadOnly(global::LightSwitchApplication.Student e)
                {
                    bool result = false;
                    e.Email_IsReadOnly(ref result);
                    return result;
                }
                private static void _Email_Validate(global::LightSwitchApplication.Student e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Email_Validate(r);
                }
                private static string _Email_GetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d)
                {
                    return d.ImplementationEntity.Email;
                }
                private static void _Email_SetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Email = v;
                }
                private static void _Email_OnValueChanged(global::LightSwitchApplication.Student e)
                {
                    e.Email_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry
                    Phone = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry(
                        "Phone",
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Phone_Stub,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Phone_ComputeIsReadOnly,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Phone_Validate,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Phone_GetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Phone_SetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Phone_OnValueChanged);
                private static void _Phone_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Student.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data> c, global::LightSwitchApplication.Student.DetailsClass d, object sf)
                {
                    c(d, ref d._Phone, sf);
                }
                private static bool _Phone_ComputeIsReadOnly(global::LightSwitchApplication.Student e)
                {
                    bool result = false;
                    e.Phone_IsReadOnly(ref result);
                    return result;
                }
                private static void _Phone_Validate(global::LightSwitchApplication.Student e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Phone_Validate(r);
                }
                private static string _Phone_GetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d)
                {
                    return d.ImplementationEntity.Phone;
                }
                private static void _Phone_SetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Phone = v;
                }
                private static void _Phone_OnValueChanged(global::LightSwitchApplication.Student e)
                {
                    e.Phone_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, byte[]>.Entry
                    Picture = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, byte[]>.Entry(
                        "Picture",
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Picture_Stub,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Picture_ComputeIsReadOnly,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Picture_Validate,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Picture_GetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Picture_SetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Picture_OnValueChanged);
                private static void _Picture_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Student.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Student.DetailsClass d, object sf)
                {
                    c(d, ref d._Picture, sf);
                }
                private static bool _Picture_ComputeIsReadOnly(global::LightSwitchApplication.Student e)
                {
                    bool result = false;
                    e.Picture_IsReadOnly(ref result);
                    return result;
                }
                private static void _Picture_Validate(global::LightSwitchApplication.Student e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Picture_Validate(r);
                }
                private static byte[] _Picture_GetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d)
                {
                    return d.ImplementationEntity.Picture;
                }
                private static void _Picture_SetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.Picture = v;
                }
                private static void _Picture_OnValueChanged(global::LightSwitchApplication.Student e)
                {
                    e.Picture_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry
                    Street = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry(
                        "Street",
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Street_Stub,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Street_ComputeIsReadOnly,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Street_Validate,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Street_GetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Street_SetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Street_OnValueChanged);
                private static void _Street_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Student.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data> c, global::LightSwitchApplication.Student.DetailsClass d, object sf)
                {
                    c(d, ref d._Street, sf);
                }
                private static bool _Street_ComputeIsReadOnly(global::LightSwitchApplication.Student e)
                {
                    bool result = false;
                    e.Street_IsReadOnly(ref result);
                    return result;
                }
                private static void _Street_Validate(global::LightSwitchApplication.Student e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Street_Validate(r);
                }
                private static string _Street_GetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d)
                {
                    return d.ImplementationEntity.Street;
                }
                private static void _Street_SetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Street = v;
                }
                private static void _Street_OnValueChanged(global::LightSwitchApplication.Student e)
                {
                    e.Street_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry
                    City = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry(
                        "City",
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._City_Stub,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._City_ComputeIsReadOnly,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._City_Validate,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._City_GetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._City_SetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._City_OnValueChanged);
                private static void _City_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Student.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data> c, global::LightSwitchApplication.Student.DetailsClass d, object sf)
                {
                    c(d, ref d._City, sf);
                }
                private static bool _City_ComputeIsReadOnly(global::LightSwitchApplication.Student e)
                {
                    bool result = false;
                    e.City_IsReadOnly(ref result);
                    return result;
                }
                private static void _City_Validate(global::LightSwitchApplication.Student e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.City_Validate(r);
                }
                private static string _City_GetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d)
                {
                    return d.ImplementationEntity.City;
                }
                private static void _City_SetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d, string v)
                {
                    d.ImplementationEntity.City = v;
                }
                private static void _City_OnValueChanged(global::LightSwitchApplication.Student e)
                {
                    e.City_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry
                    State = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry(
                        "State",
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._State_Stub,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._State_ComputeIsReadOnly,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._State_Validate,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._State_GetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._State_SetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._State_OnValueChanged);
                private static void _State_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Student.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data> c, global::LightSwitchApplication.Student.DetailsClass d, object sf)
                {
                    c(d, ref d._State, sf);
                }
                private static bool _State_ComputeIsReadOnly(global::LightSwitchApplication.Student e)
                {
                    bool result = false;
                    e.State_IsReadOnly(ref result);
                    return result;
                }
                private static void _State_Validate(global::LightSwitchApplication.Student e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.State_Validate(r);
                }
                private static string _State_GetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d)
                {
                    return d.ImplementationEntity.State;
                }
                private static void _State_SetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d, string v)
                {
                    d.ImplementationEntity.State = v;
                }
                private static void _State_OnValueChanged(global::LightSwitchApplication.Student e)
                {
                    e.State_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry
                    Zip = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry(
                        "Zip",
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Zip_Stub,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Zip_ComputeIsReadOnly,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Zip_Validate,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Zip_GetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Zip_SetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Zip_OnValueChanged);
                private static void _Zip_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Student.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data> c, global::LightSwitchApplication.Student.DetailsClass d, object sf)
                {
                    c(d, ref d._Zip, sf);
                }
                private static bool _Zip_ComputeIsReadOnly(global::LightSwitchApplication.Student e)
                {
                    bool result = false;
                    e.Zip_IsReadOnly(ref result);
                    return result;
                }
                private static void _Zip_Validate(global::LightSwitchApplication.Student e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Zip_Validate(r);
                }
                private static string _Zip_GetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d)
                {
                    return d.ImplementationEntity.Zip;
                }
                private static void _Zip_SetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Zip = v;
                }
                private static void _Zip_OnValueChanged(global::LightSwitchApplication.Student e)
                {
                    e.Zip_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::System.DateTime>.Entry
                    CreatedTime = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::System.DateTime>.Entry(
                        "CreatedTime",
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._CreatedTime_Stub,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._CreatedTime_ComputeIsReadOnly,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._CreatedTime_Validate,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._CreatedTime_GetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._CreatedTime_SetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._CreatedTime_OnValueChanged);
                private static void _CreatedTime_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Student.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.Student.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedTime, sf);
                }
                private static bool _CreatedTime_ComputeIsReadOnly(global::LightSwitchApplication.Student e)
                {
                    bool result = false;
                    e.CreatedTime_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedTime_Validate(global::LightSwitchApplication.Student e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedTime_Validate(r);
                }
                private static global::System.DateTime _CreatedTime_GetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedTime;
                }
                private static void _CreatedTime_SetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.CreatedTime = global::LightSwitchApplication.Student.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _CreatedTime_OnValueChanged(global::LightSwitchApplication.Student e)
                {
                    e.CreatedTime_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::System.DateTime>.Entry
                    UpdatedTime = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::System.DateTime>.Entry(
                        "UpdatedTime",
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._UpdatedTime_Stub,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._UpdatedTime_ComputeIsReadOnly,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._UpdatedTime_Validate,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._UpdatedTime_GetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._UpdatedTime_SetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._UpdatedTime_OnValueChanged);
                private static void _UpdatedTime_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Student.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.Student.DetailsClass d, object sf)
                {
                    c(d, ref d._UpdatedTime, sf);
                }
                private static bool _UpdatedTime_ComputeIsReadOnly(global::LightSwitchApplication.Student e)
                {
                    bool result = false;
                    e.UpdatedTime_IsReadOnly(ref result);
                    return result;
                }
                private static void _UpdatedTime_Validate(global::LightSwitchApplication.Student e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.UpdatedTime_Validate(r);
                }
                private static global::System.DateTime _UpdatedTime_GetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d)
                {
                    return d.ImplementationEntity.UpdatedTime;
                }
                private static void _UpdatedTime_SetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.UpdatedTime = global::LightSwitchApplication.Student.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _UpdatedTime_OnValueChanged(global::LightSwitchApplication.Student e)
                {
                    e.UpdatedTime_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry
                    UpdatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry(
                        "UpdatedBy",
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._UpdatedBy_Stub,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._UpdatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._UpdatedBy_Validate,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._UpdatedBy_GetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._UpdatedBy_SetImplementationValue,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._UpdatedBy_OnValueChanged);
                private static void _UpdatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Student.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data> c, global::LightSwitchApplication.Student.DetailsClass d, object sf)
                {
                    c(d, ref d._UpdatedBy, sf);
                }
                private static bool _UpdatedBy_ComputeIsReadOnly(global::LightSwitchApplication.Student e)
                {
                    bool result = false;
                    e.UpdatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _UpdatedBy_Validate(global::LightSwitchApplication.Student e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.UpdatedBy_Validate(r);
                }
                private static string _UpdatedBy_GetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d)
                {
                    return d.ImplementationEntity.UpdatedBy;
                }
                private static void _UpdatedBy_SetImplementationValue(global::LightSwitchApplication.Student.DetailsClass d, string v)
                {
                    d.ImplementationEntity.UpdatedBy = v;
                }
                private static void _UpdatedBy_OnValueChanged(global::LightSwitchApplication.Student e)
                {
                    e.UpdatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry
                    Summary = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Entry(
                        "Summary",
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Summary_Stub,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Summary_Validate,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Summary_ComputeValue);
                private static void _Summary_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Student.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data> c, global::LightSwitchApplication.Student.DetailsClass d, object sf)
                {
                    c(d, ref d._Summary, sf);
                }
                private static void _Summary_Validate(global::LightSwitchApplication.Student e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Summary_Validate(r);
                }
                private static string _Summary_ComputeValue(global::LightSwitchApplication.Student e)
                {
                    string value = default(string);
                    e.Summary_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::LightSwitchApplication.Enrollment>.Entry
                    Enrollments = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::LightSwitchApplication.Enrollment>.Entry(
                        "Enrollments",
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Enrollments_Stub,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Enrollments_GetReferencedEntities,
                        global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties._Enrollments_GetEntityCollection);
                private static void _Enrollments_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Student.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::LightSwitchApplication.Enrollment>.Data> c, global::LightSwitchApplication.Student.DetailsClass d, object sf)
                {
                    c(d, ref d._Enrollments, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Enrollment> _Enrollments_GetReferencedEntities(global::LightSwitchApplication.Student.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Enrollment, global::LightSwitchApplication.Enrollment.DetailsClass>(global::LightSwitchApplication.Student.DetailsClass.PropertySetProperties.Enrollments, ref d._Enrollments);
                }
                private static global::System.Collections.IEnumerable _Enrollments_GetEntityCollection(global::LightSwitchApplication.Student.DetailsClass d)
                {
                    return d.ImplementationEntity.Enrollments;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data _FirstName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data _LastName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data _Email;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data _Phone;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, byte[]>.Data _Picture;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data _Street;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data _City;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data _State;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data _Zip;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::System.DateTime>.Data _CreatedTime;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::System.DateTime>.Data _UpdatedTime;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data _UpdatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, string>.Data _Summary;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass, global::LightSwitchApplication.Enrollment>.Data _Enrollments;
            
        }
    
        #endregion
    }
    
    #endregion
}
