

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class CourseCategory : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass>
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public CourseCategory()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public CourseCategory(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.CourseCategory> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.CourseCategory.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CourseCategory_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CourseCategory_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.CourseCategory.DetailsClass.GetValue(this, global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.CourseCategory.DetailsClass.SetValue(this, global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Summary
        {
            get
            {
                return global::LightSwitchApplication.CourseCategory.DetailsClass.GetValue(this, global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties.Summary);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Summary_Compute(ref string result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Summary_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Course Course
        {
            get
            {
                return global::LightSwitchApplication.CourseCategory.DetailsClass.GetValue(this, global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties.Course);
            }
            set
            {
                global::LightSwitchApplication.CourseCategory.DetailsClass.SetValue(this, global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties.Course, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Course_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Course_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Course_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Category Category
        {
            get
            {
                return global::LightSwitchApplication.CourseCategory.DetailsClass.GetValue(this, global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties.Category);
            }
            set
            {
                global::LightSwitchApplication.CourseCategory.DetailsClass.SetValue(this, global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties.Category, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Category_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Category_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Category_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.CourseCategory,
                global::LightSwitchApplication.CourseCategory.DetailsClass,
                global::LightSwitchApplication.CourseCategory.DetailsClass.IImplementation,
                global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass>.Entry
                __CourseCategoryEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass>.Entry(
                    global::LightSwitchApplication.CourseCategory.DetailsClass.__CourseCategory_CreateNew,
                    global::LightSwitchApplication.CourseCategory.DetailsClass.__CourseCategory_Created,
                    global::LightSwitchApplication.CourseCategory.DetailsClass.__CourseCategory_AllowSaveWithErrors);
            private static global::LightSwitchApplication.CourseCategory __CourseCategory_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.CourseCategory> es)
            {
                return new global::LightSwitchApplication.CourseCategory(es);
            }
            private static void __CourseCategory_Created(global::LightSwitchApplication.CourseCategory e)
            {
                e.CourseCategory_Created();
            }
            private static bool __CourseCategory_AllowSaveWithErrors(global::LightSwitchApplication.CourseCategory e)
            {
                bool result = false;
                e.CourseCategory_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass, string> Summary
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties.Summary) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass, global::LightSwitchApplication.Course> Course
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties.Course) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass, global::LightSwitchApplication.Course>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass, global::LightSwitchApplication.Category> Category
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties.Category) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass, global::LightSwitchApplication.Category>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Course { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Category { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CourseCategory.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass, int>.Data> c, global::LightSwitchApplication.CourseCategory.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.CourseCategory e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.CourseCategory e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.CourseCategory.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.CourseCategory.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.CourseCategory e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass, string>.Entry
                    Summary = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass, string>.Entry(
                        "Summary",
                        global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties._Summary_Stub,
                        global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties._Summary_Validate,
                        global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties._Summary_ComputeValue);
                private static void _Summary_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CourseCategory.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass, string>.Data> c, global::LightSwitchApplication.CourseCategory.DetailsClass d, object sf)
                {
                    c(d, ref d._Summary, sf);
                }
                private static void _Summary_Validate(global::LightSwitchApplication.CourseCategory e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Summary_Validate(r);
                }
                private static string _Summary_ComputeValue(global::LightSwitchApplication.CourseCategory e)
                {
                    string value = default(string);
                    e.Summary_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass, global::LightSwitchApplication.Course>.Entry
                    Course = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass, global::LightSwitchApplication.Course>.Entry(
                        "Course",
                        global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties._Course_Stub,
                        global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties._Course_ComputeIsReadOnly,
                        global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties._Course_Validate,
                        global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties._Course_GetImplementationValue,
                        global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties._Course_SetImplementationValue,
                        global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties._Course_Refresh,
                        global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties._Course_OnValueChanged);
                private static void _Course_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CourseCategory.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass, global::LightSwitchApplication.Course>.Data> c, global::LightSwitchApplication.CourseCategory.DetailsClass d, object sf)
                {
                    c(d, ref d._Course, sf);
                }
                private static bool _Course_ComputeIsReadOnly(global::LightSwitchApplication.CourseCategory e)
                {
                    bool result = false;
                    e.Course_IsReadOnly(ref result);
                    return result;
                }
                private static void _Course_Validate(global::LightSwitchApplication.CourseCategory e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Course_Validate(r);
                }
                private static global::LightSwitchApplication.Course _Course_GetImplementationValue(global::LightSwitchApplication.CourseCategory.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Course, global::LightSwitchApplication.Course.DetailsClass>(global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties.Course, ref d._Course, i => i.Course);
                }
                private static void _Course_SetImplementationValue(global::LightSwitchApplication.CourseCategory.DetailsClass d, global::LightSwitchApplication.Course v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties.Course, ref d._Course, (i, ev) => i.Course = ev, v);
                }
                private static void _Course_Refresh(global::LightSwitchApplication.CourseCategory.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties.Course, ref d._Course, i => i.Course);
                }
                private static void _Course_OnValueChanged(global::LightSwitchApplication.CourseCategory e)
                {
                    e.Course_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass, global::LightSwitchApplication.Category>.Entry
                    Category = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass, global::LightSwitchApplication.Category>.Entry(
                        "Category",
                        global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties._Category_Stub,
                        global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties._Category_ComputeIsReadOnly,
                        global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties._Category_Validate,
                        global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties._Category_GetImplementationValue,
                        global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties._Category_SetImplementationValue,
                        global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties._Category_Refresh,
                        global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties._Category_OnValueChanged);
                private static void _Category_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CourseCategory.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass, global::LightSwitchApplication.Category>.Data> c, global::LightSwitchApplication.CourseCategory.DetailsClass d, object sf)
                {
                    c(d, ref d._Category, sf);
                }
                private static bool _Category_ComputeIsReadOnly(global::LightSwitchApplication.CourseCategory e)
                {
                    bool result = false;
                    e.Category_IsReadOnly(ref result);
                    return result;
                }
                private static void _Category_Validate(global::LightSwitchApplication.CourseCategory e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Category_Validate(r);
                }
                private static global::LightSwitchApplication.Category _Category_GetImplementationValue(global::LightSwitchApplication.CourseCategory.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Category, global::LightSwitchApplication.Category.DetailsClass>(global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties.Category, ref d._Category, i => i.Category);
                }
                private static void _Category_SetImplementationValue(global::LightSwitchApplication.CourseCategory.DetailsClass d, global::LightSwitchApplication.Category v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties.Category, ref d._Category, (i, ev) => i.Category = ev, v);
                }
                private static void _Category_Refresh(global::LightSwitchApplication.CourseCategory.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.CourseCategory.DetailsClass.PropertySetProperties.Category, ref d._Category, i => i.Category);
                }
                private static void _Category_OnValueChanged(global::LightSwitchApplication.CourseCategory e)
                {
                    e.Category_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass, string>.Data _Summary;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass, global::LightSwitchApplication.Course>.Data _Course;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.CourseCategory, global::LightSwitchApplication.CourseCategory.DetailsClass, global::LightSwitchApplication.Category>.Data _Category;
            
        }
    
        #endregion
    }
    
    #endregion
}
