

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class Enrollment : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Enrollment, global::LightSwitchApplication.Enrollment.DetailsClass>
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Enrollment()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Enrollment(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Enrollment> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Enrollment.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Enrollment_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Enrollment_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Enrollment.DetailsClass.GetValue(this, global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Enrollment.DetailsClass.SetValue(this, global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Section Section
        {
            get
            {
                return global::LightSwitchApplication.Enrollment.DetailsClass.GetValue(this, global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties.Section);
            }
            set
            {
                global::LightSwitchApplication.Enrollment.DetailsClass.SetValue(this, global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties.Section, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Section_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Section_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Section_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Student Student
        {
            get
            {
                return global::LightSwitchApplication.Enrollment.DetailsClass.GetValue(this, global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties.Student);
            }
            set
            {
                global::LightSwitchApplication.Enrollment.DetailsClass.SetValue(this, global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties.Student, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Student_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Student_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Student_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Enrollment,
                global::LightSwitchApplication.Enrollment.DetailsClass,
                global::LightSwitchApplication.Enrollment.DetailsClass.IImplementation,
                global::LightSwitchApplication.Enrollment.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Enrollment, global::LightSwitchApplication.Enrollment.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Enrollment, global::LightSwitchApplication.Enrollment.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Enrollment, global::LightSwitchApplication.Enrollment.DetailsClass>.Entry
                __EnrollmentEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Enrollment, global::LightSwitchApplication.Enrollment.DetailsClass>.Entry(
                    global::LightSwitchApplication.Enrollment.DetailsClass.__Enrollment_CreateNew,
                    global::LightSwitchApplication.Enrollment.DetailsClass.__Enrollment_Created,
                    global::LightSwitchApplication.Enrollment.DetailsClass.__Enrollment_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Enrollment __Enrollment_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Enrollment> es)
            {
                return new global::LightSwitchApplication.Enrollment(es);
            }
            private static void __Enrollment_Created(global::LightSwitchApplication.Enrollment e)
            {
                e.Enrollment_Created();
            }
            private static bool __Enrollment_AllowSaveWithErrors(global::LightSwitchApplication.Enrollment e)
            {
                bool result = false;
                e.Enrollment_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Enrollment, global::LightSwitchApplication.Enrollment.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Enrollment, global::LightSwitchApplication.Enrollment.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Enrollment.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Enrollment, global::LightSwitchApplication.Enrollment.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Enrollment, global::LightSwitchApplication.Enrollment.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Enrollment, global::LightSwitchApplication.Enrollment.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Enrollment, global::LightSwitchApplication.Enrollment.DetailsClass, global::LightSwitchApplication.Section> Section
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties.Section) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Enrollment, global::LightSwitchApplication.Enrollment.DetailsClass, global::LightSwitchApplication.Section>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Enrollment, global::LightSwitchApplication.Enrollment.DetailsClass, global::LightSwitchApplication.Student> Student
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties.Student) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Enrollment, global::LightSwitchApplication.Enrollment.DetailsClass, global::LightSwitchApplication.Student>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Section { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Student { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Enrollment, global::LightSwitchApplication.Enrollment.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Enrollment, global::LightSwitchApplication.Enrollment.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Enrollment.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Enrollment, global::LightSwitchApplication.Enrollment.DetailsClass, int>.Data> c, global::LightSwitchApplication.Enrollment.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Enrollment e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Enrollment e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Enrollment.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Enrollment.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Enrollment e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Enrollment, global::LightSwitchApplication.Enrollment.DetailsClass, global::LightSwitchApplication.Section>.Entry
                    Section = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Enrollment, global::LightSwitchApplication.Enrollment.DetailsClass, global::LightSwitchApplication.Section>.Entry(
                        "Section",
                        global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties._Section_Stub,
                        global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties._Section_ComputeIsReadOnly,
                        global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties._Section_Validate,
                        global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties._Section_GetImplementationValue,
                        global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties._Section_SetImplementationValue,
                        global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties._Section_Refresh,
                        global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties._Section_OnValueChanged);
                private static void _Section_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Enrollment.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Enrollment, global::LightSwitchApplication.Enrollment.DetailsClass, global::LightSwitchApplication.Section>.Data> c, global::LightSwitchApplication.Enrollment.DetailsClass d, object sf)
                {
                    c(d, ref d._Section, sf);
                }
                private static bool _Section_ComputeIsReadOnly(global::LightSwitchApplication.Enrollment e)
                {
                    bool result = false;
                    e.Section_IsReadOnly(ref result);
                    return result;
                }
                private static void _Section_Validate(global::LightSwitchApplication.Enrollment e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Section_Validate(r);
                }
                private static global::LightSwitchApplication.Section _Section_GetImplementationValue(global::LightSwitchApplication.Enrollment.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Section, global::LightSwitchApplication.Section.DetailsClass>(global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties.Section, ref d._Section, i => i.Section);
                }
                private static void _Section_SetImplementationValue(global::LightSwitchApplication.Enrollment.DetailsClass d, global::LightSwitchApplication.Section v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties.Section, ref d._Section, (i, ev) => i.Section = ev, v);
                }
                private static void _Section_Refresh(global::LightSwitchApplication.Enrollment.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties.Section, ref d._Section, i => i.Section);
                }
                private static void _Section_OnValueChanged(global::LightSwitchApplication.Enrollment e)
                {
                    e.Section_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Enrollment, global::LightSwitchApplication.Enrollment.DetailsClass, global::LightSwitchApplication.Student>.Entry
                    Student = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Enrollment, global::LightSwitchApplication.Enrollment.DetailsClass, global::LightSwitchApplication.Student>.Entry(
                        "Student",
                        global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties._Student_Stub,
                        global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties._Student_ComputeIsReadOnly,
                        global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties._Student_Validate,
                        global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties._Student_GetImplementationValue,
                        global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties._Student_SetImplementationValue,
                        global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties._Student_Refresh,
                        global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties._Student_OnValueChanged);
                private static void _Student_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Enrollment.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Enrollment, global::LightSwitchApplication.Enrollment.DetailsClass, global::LightSwitchApplication.Student>.Data> c, global::LightSwitchApplication.Enrollment.DetailsClass d, object sf)
                {
                    c(d, ref d._Student, sf);
                }
                private static bool _Student_ComputeIsReadOnly(global::LightSwitchApplication.Enrollment e)
                {
                    bool result = false;
                    e.Student_IsReadOnly(ref result);
                    return result;
                }
                private static void _Student_Validate(global::LightSwitchApplication.Enrollment e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Student_Validate(r);
                }
                private static global::LightSwitchApplication.Student _Student_GetImplementationValue(global::LightSwitchApplication.Enrollment.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Student, global::LightSwitchApplication.Student.DetailsClass>(global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties.Student, ref d._Student, i => i.Student);
                }
                private static void _Student_SetImplementationValue(global::LightSwitchApplication.Enrollment.DetailsClass d, global::LightSwitchApplication.Student v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties.Student, ref d._Student, (i, ev) => i.Student = ev, v);
                }
                private static void _Student_Refresh(global::LightSwitchApplication.Enrollment.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Enrollment.DetailsClass.PropertySetProperties.Student, ref d._Student, i => i.Student);
                }
                private static void _Student_OnValueChanged(global::LightSwitchApplication.Enrollment e)
                {
                    e.Student_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Enrollment, global::LightSwitchApplication.Enrollment.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Enrollment, global::LightSwitchApplication.Enrollment.DetailsClass, global::LightSwitchApplication.Section>.Data _Section;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Enrollment, global::LightSwitchApplication.Enrollment.DetailsClass, global::LightSwitchApplication.Student>.Data _Student;
            
        }
    
        #endregion
    }
    
    #endregion
}
